2019-05-08 16:18:48,294 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:140]
2019-05-08 16:19:35,911 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:140]
2019-05-08 16:20:24,418 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:140]
2019-05-08 16:39:19,119 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:162]
2019-05-08 16:39:37,416 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:162]
2019-05-08 17:02:49,883 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:162]
2019-05-08 17:17:13,211 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:162]
2019-05-08 17:33:35,938 INFO: Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:162]
2019-05-09 08:55:03,722 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 08:55:34,643 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 08:56:01,768 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 08:56:01,772 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 08:56:01,772 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 08:59:07,593 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 09:00:26,856 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 09:02:38,927 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 09:05:18,251 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 09:05:23,967 ERROR: Exception on /auth/login [GET] [in C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Darie\Desktop\microblog\app\auth\routes.py", line 67, in login
    return render_template('auth.login.html', title='Sign In', form=form)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth.login.html
2019-05-09 09:06:40,044 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
2019-05-09 09:06:41,637 ERROR: Exception on /auth/login [GET] [in C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Darie\Desktop\microblog\app\auth\routes.py", line 67, in login
    return render_template('auth.login.html', title='Sign In', form=form)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth.login.html
2019-05-09 09:07:32,904 ERROR: Exception on /auth/login [GET] [in C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Darie\Desktop\microblog\app\auth\routes.py", line 67, in login
    return render_template('auth.login.html', title='Sign In', form=form)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\ProgramData\Anaconda3\envs\flask_env\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth.login.html
2019-05-09 09:09:33,796 INFO: Acorn's Microblog startup [in C:\Users\Darie\Desktop\microblog\app\__init__.py:218]
